name = "HoJBot"
uuid = "7918a2cc-0dd0-4d51-b3de-26cf4b7ed9a1"
authors = ["Tom Kwong <tk3369@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Discord = "fcbf000d-02fd-53f1-af91-d952191673d3"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
ExpiringCaches = "bd5c46ae-da38-4b10-bcdd-5005402f2c4f"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PlotThemes = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pretend = "8ad1c615-040c-41b0-a18f-ae9e9fd09b5b"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
CSV = "0.8"
DataFrames = "1.0"
ExpiringCaches = "1.1"
Formatting = "0.4"
HTTP = "0.9"
JSON = "0.21"
JSON3 = "1.8"
OrderedCollections = "1.4"
PlotThemes = "2.0"
Plots = "1.13"
Pretend = "1.0"
PrettyTables = "1.0"
PyPlot = "2.9"
StructTypes = "1.5"
TimeZones = "1.5"
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
